exp_name: base_mobile_black
parent_cfg: configs/base.yaml

# Data options
train_dataset:
    data_root: data/mobile_stage/black
    human: model2
    ann_file: annots.npy
    split: train

test_dataset:
    data_root: data/mobile_stage/black
    human: model2
    ann_file: annots.npy
    split: test

mask: rvm

# Selection Options
# prettier-ignore
training_view: [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33] # 12 views
# prettier-ignore
test_view: [] # will use all view except training views
fix_material: 0
begin_ith_frame: 0
num_train_frame: 300 # only 400 valid frames
num_eval_frame: 400
num_render_view: 100
test:
    view_sampler_interval: 8
    frame_sampler_interval: 60

# Relighting Configuration
relighting_cfg:
    exp_name: relight_mobile_black
    geometry_mesh: data/animation/deform/base_mobile_black/can_mesh.npz
    geometry_pretrain: data/trained_model/deform/base_mobile_black
